### PR TITLE
Feature/42a inaccurate fdpm amplitude and phase derivative values with respect to mu a and mu s

### PR DESCRIPTION
**Pull request by hayakawa16**
Draft of PR started so I can check code cleanup.

### CODE REVIEW

**Comment by hayakawa16** [comment]
I have fixed the code coverage percentage to 93.3% and now passes.  I think the checks are not passing due to the new issues.  I will work on those this week.  The code can be tried at this point though.  I would like to make sure I didn't miss anything with regards to the derivatives if possible.

**Comment by lmalenfant** [comment]
The quality gate failed for this branch, there are 4 code smells, I think 2 can be easily fixed, once we do that we can reassess the quality gate to see if it still fails, if it does we might be able to change the parameters until we can clean up the code more.

**Comment by hayakawa16** [comment]
@lmalenfant, would you possibly be able to fix those code smells?  If not, I can do later this week.

**Comment by hayakawa16** [comment]
Great work @lmalenfant!  Thanks.

**Comment by lmalenfant** [comment]
@hayakawa16 when you get a chance, could you pull the latest and try out the log plots and let me know if this looks good to you.

**Comment by hayakawa16** [comment]
Hi @lmalenfant, I tried log plots both in x and y, and ticks look good.  Are you still noticing something incorrect?

**Comment by lmalenfant** [comment]
@hayakawa16 I think everything looks good, I was running tests at the same time as running the GUI and I think that may have caused some issues.

I tested several plots yesterday and they all looked good.

**Comment by lmalenfant** [comment]
Added the new VTS library and now I can get the Phase and Amplitude derivative values.

Phase:
image

Amplitude:
image

**Review by lmalenfant — APPROVED** [review]

**Pull request merged**
