### PR TITLE
Update NuGet packages and fix the OxyPlot breaking changes

### PR DESCRIPTION
**Pull request by lmalenfant**

### CODE REVIEW

**Comment by lmalenfant** [comment]
I pulled in the new OxyPlot package 2.1.2 and fixed the breaking changes (these were the same as version 2.1.1), the pop out window is working again in this version and there don't appear to be any other plot issues.

**Review by hayakawa16 — APPROVED** [review]
Reviewing changes shows that new code was in place already (in comments) in preparation for OxyPlot bug fix?

**Comment by hayakawa16** [comment]
Sounds great!

**Comment by lmalenfant** [comment]
> Reviewing changes shows that new code was in place already (in comments) in preparation for OxyPlot bug fix?

Yes exactly, luckily there were no additional breaking changes.

**Pull request merged**
